name: marco-mancastroppa.github.io
title: Marco Mancastroppa
description: Physicist, working on Complex Systems, Networks and Data Science.
remote_theme: pages-themes/cayman@v0.2.0
plugins: 
- jekyll-remote-theme 
